import {createContext,useContext,useEffect,useMemo,useState} from 'react';

const LanguageContext=createContext(null);

const HI={
  'Welcome back':'वापसी पर स्वागत है','Direct farm-to-market, trusted delivery.':'सीधे खेत से बाजार तक, भरोसेमंद डिलीवरी।','Backend-ready prototype':'बैकएंड-तैयार प्रोटोटाइप',
  'Use the seeded accounts to explore the complete buyer, farmer, driver and admin workflow.':'पहले से दिए गए खातों से खरीदार, किसान, ड्राइवर और एडमिन का पूरा वर्कफ़्लो देखें।',
  'Email':'ईमेल','Password':'पासवर्ड','Sign in':'साइन इन','Signing in…':'साइन इन हो रहा है…','or explore instantly as':'या तुरंत इस भूमिका में देखें',
  'Buyer':'खरीदार','Farmer':'किसान','Truck Driver':'ट्रक ड्राइवर','Admin demo':'एडमिन डेमो','New here?':'नए हैं?','Create an account':'खाता बनाएं','Home':'होम',
  'Get started':'शुरू करें','Sign in →':'साइन इन →','Logout':'लॉग आउट','FRONTEND DEMO':'फ्रंटएंड डेमो','Choose your role':'अपनी भूमिका चुनें',
  'List produce & manage orders':'उपज सूचीबद्ध करें और ऑर्डर प्रबंधित करें','Accept loads & deliver':'लोड स्वीकार करें और डिलीवरी करें','Find produce & place orders':'उपज खोजें और ऑर्डर करें','Continue →':'जारी रखें →',
  'Tell us about you':'अपने बारे में बताएं','Full name':'पूरा नाम','Region / City':'क्षेत्र / शहर','Continue to verification →':'सत्यापन पर जाएं →',
  'DOCUMENT VERIFICATION':'दस्तावेज़ सत्यापन','Upload proof':'प्रमाण अपलोड करें','Identity / Aadhaar':'पहचान / आधार','Role document':'भूमिका संबंधी दस्तावेज़','Bank / payment proof':'बैंक / भुगतान प्रमाण','Image or document':'छवि या दस्तावेज़',
  'Verify & continue →':'सत्यापित करें और जारी रखें →','Verification complete':'सत्यापन पूरा हुआ','Enter KhetConnect →':'KhetConnect में प्रवेश करें →',
  'Your prototype account is ready. You can now explore every role feature without a backend.':'आपका प्रोटोटाइप खाता तैयार है। अब आप बिना बैकएंड के सभी भूमिका सुविधाएं देख सकते हैं।',
  'BUYER HUB':'खरीदार केंद्र','FARMER HUB':'किसान केंद्र','LOGISTICS HUB':'लॉजिस्टिक्स केंद्र','Welcome,':'स्वागत है,','Discover verified farmers, place orders and compare trusted produce.':'सत्यापित किसानों को खोजें, ऑर्डर करें और भरोसेमंद उपज की तुलना करें।',
  'Find fresh produce':'ताज़ी उपज खोजें','DIRECT FARM MARKET · RANKED BY TRUST':'सीधा किसान बाजार · भरोसे के आधार पर रैंक','Search crops and farmers. Higher verified-order ratings are recommended first, while certificate status and declared quality remain visible.':'फसल और किसानों को खोजें। अधिक सत्यापित ऑर्डर रेटिंग वाले किसानों को पहले सुझाया जाता है, जबकि प्रमाणपत्र स्थिति और घोषित गुणवत्ता दिखाई देती रहती है।',
  'Search onion, mango, farmer, region...':'प्याज़, आम, किसान, क्षेत्र खोजें...','All India':'पूरा भारत','Recommended first':'पहले अनुशंसित','Farmer rating + completed-order review history influence ranking.':'किसान रेटिंग और पूरे हुए ऑर्डरों की समीक्षा इतिहास रैंकिंग को प्रभावित करता है।','Escrow protected':'एस्क्रो सुरक्षित','Payment is held until buyer confirms receipt.':'खरीदार द्वारा प्राप्ति की पुष्टि तक भुगतान सुरक्षित रखा जाता है।','Honest grading':'ईमानदार ग्रेडिंग','Grade is farmer-declared unless certificate/inspection is verified.':'जब तक प्रमाणपत्र/निरीक्षण सत्यापित न हो, ग्रेड किसान द्वारा घोषित माना जाता है।',
  'Start Order':'ऑर्डर शुरू करें','ORDER PREVIEW · ESCROW':'ऑर्डर पूर्वावलोकन · एस्क्रो','Place order':'ऑर्डर करें','Quantity':'मात्रा','Available':'उपलब्ध','Delivery':'डिलीवरी','Estimated delivery':'अनुमानित डिलीवरी','days':'दिन','Total escrow':'कुल एस्क्रो','Payment held securely until receipt confirmation.':'प्राप्ति की पुष्टि तक भुगतान सुरक्षित रखा जाता है।',
  'Orders & Escrow':'ऑर्डर और एस्क्रो','MY PURCHASES':'मेरी खरीदारी','Track farmer acceptance, transport, receipt confirmation and escrow release.':'किसान की स्वीकृति, परिवहन, प्राप्ति की पुष्टि और एस्क्रो रिलीज़ को ट्रैक करें।','No orders yet':'अभी कोई ऑर्डर नहीं','Browse & Start an Order':'ब्राउज़ करें और ऑर्डर शुरू करें',
  'List your crop / produce':'अपनी फसल / उपज सूचीबद्ध करें','SELL WITH TRANSPARENCY':'पारदर्शिता के साथ बेचें','Farmers declare quality using measurable parameters. Buyers see exactly what was declared and whether a certificate is only uploaded or verified.':'किसान मापने योग्य मानकों के आधार पर गुणवत्ता घोषित करते हैं। खरीदार देख सकते हैं कि क्या घोषित किया गया और प्रमाणपत्र केवल अपलोड हुआ है या सत्यापित भी है।',
  'Produce details':'उपज विवरण','What are you selling?':'आप क्या बेच रहे हैं?','Crop / product':'फसल / उत्पाद','Available quantity (kg)':'उपलब्ध मात्रा (किग्रा)','Quality declaration':'गुणवत्ता घोषणा','This is a farmer declaration, not an automatic lab certification.':'यह किसान की घोषणा है, स्वचालित लैब प्रमाणन नहीं।','How Grade':'ग्रेड कैसे निर्धारित होता है','Farmer Declared':'किसान द्वारा घोषित','Quality grade':'गुणवत्ता ग्रेड','Maturity':'परिपक्वता','Appearance / uniformity':'दिखावट / एकरूपता','Damaged produce %':'क्षतिग्रस्त उपज %','Moisture %':'नमी %','Pest / disease damage':'कीट / रोग क्षति','Foreign matter %':'बाहरी पदार्थ %','Harvest date':'कटाई की तारीख',
  'Produce photo & certification':'उपज फोटो और प्रमाणपत्र','Photos help buyers cross-check what they receive.':'फोटो खरीदारों को प्राप्त उपज से तुलना करने में मदद करती हैं।','Crop / produce photo':'फसल / उपज फोटो','JPG/PNG · prototype preview':'JPG/PNG · प्रोटोटाइप पूर्वावलोकन','Buyer preview':'खरीदार पूर्वावलोकन','Certificate uploaded · Pending Admin Verification':'प्रमाणपत्र अपलोड · एडमिन सत्यापन लंबित','No special certification claimed':'कोई विशेष प्रमाणन दावा नहीं','Crop photo added':'फसल फोटो जोड़ी गई','Crop photo not added':'फसल फोटो नहीं जोड़ी गई','Publish Listing →':'लिस्टिंग प्रकाशित करें →','Listing published. Buyers can now see the declared quality basis, photo and certificate status.':'लिस्टिंग प्रकाशित हो गई। खरीदार अब घोषित गुणवत्ता आधार, फोटो और प्रमाणपत्र स्थिति देख सकते हैं।',
  'FARMER ACTION':'किसान की कार्रवाई','Accept this buyer order':'इस खरीदार ऑर्डर को स्वीकार करें','Confirm the quantity and start arranging trusted transport.':'मात्रा की पुष्टि करें और भरोसेमंद परिवहन की व्यवस्था शुरू करें।','Accept order':'ऑर्डर स्वीकार करें','Create transport job':'परिवहन जॉब बनाएं','Transport days':'परिवहन के दिन','Driver wage':'ड्राइवर मजदूरी','Pickup':'पिकअप','Destination':'गंतव्य','Accepted':'स्वीकृत','Pending':'लंबित','Delivered':'डिलीवर हो गया','In transit':'रास्ते में','Picked up':'पिकअप हो गया',
  'DRIVER ACTIVITY':'ड्राइवर गतिविधि','My trips':'मेरी यात्राएं','Accepted transport jobs and their current status.':'स्वीकृत परिवहन जॉब और उनकी वर्तमान स्थिति।','Available Loads':'उपलब्ध लोड','View Available Loads →':'उपलब्ध लोड देखें →','Accept Job':'जॉब स्वीकार करें','Available transport jobs':'उपलब्ध परिवहन जॉब','Route':'मार्ग','Wage':'मजदूरी','Vehicle':'वाहन',
  'FARMER GROWTH':'किसान विकास','Where to sell':'कहां बेचें','Match your produce with high-demand regions and direct buyers.':'अपनी उपज को अधिक मांग वाले क्षेत्रों और सीधे खरीदारों से मिलाएं।','Demand intelligence':'मांग जानकारी','Cost estimator':'लागत अनुमानक','Price Trends':'कीमत रुझान','Regional stats':'क्षेत्रीय आंकड़े','Where is demand?':'मांग कहां है?','Explore regional demand signals across India. This is a presentation-ready data view.':'पूरे भारत में क्षेत्रीय मांग संकेत देखें। यह प्रस्तुति के लिए तैयार डेटा दृश्य है।',
  'Price trends':'कीमत रुझान','MARKET SIGNAL':'बाजार संकेत','Update':'अपडेट करें','REGIONAL VIEW':'क्षेत्रीय दृश्य','Quick view of leading produce categories by destination region.':'गंतव्य क्षेत्र के अनुसार प्रमुख उपज श्रेणियों का त्वरित दृश्य।','INDIA DEMAND MAP':'भारत मांग मानचित्र','Demand Insights':'मांग जानकारी','FARMER DEMAND INTELLIGENCE':'किसान मांग जानकारी','High-demand crops, flowers and farm products by region.':'क्षेत्र के अनुसार अधिक मांग वाली फसलें, फूल और कृषि उत्पाद।','All regions':'सभी क्षेत्र',
  'TRUSTED LOGISTICS':'भरोसेमंद लॉजिस्टिक्स','Find a truck driver':'ट्रक ड्राइवर खोजें','Drivers show route experience, vehicle, verification and rating.':'ड्राइवर मार्ग अनुभव, वाहन, सत्यापन और रेटिंग दिखाते हैं।','Track delivery':'डिलीवरी ट्रैक करें','LIVE DEMO TRACKING':'लाइव डेमो ट्रैकिंग','Role-neutral delivery timeline for the prototype.':'प्रोटोटाइप के लिए भूमिका-निरपेक्ष डिलीवरी टाइमलाइन।',
  'Confirm delivery received':'डिलीवरी प्राप्त होने की पुष्टि करें','Release escrow to farmer':'किसान को एस्क्रो भुगतान जारी करें','Raise dispute':'विवाद दर्ज करें','Rate driver':'ड्राइवर को रेट करें','On-time delivery':'समय पर डिलीवरी','Product quality':'उत्पाद गुणवत्ता','Farmer feedback':'किसान प्रतिक्रिया','Write your feedback':'अपनी प्रतिक्रिया लिखें','Submit review':'समीक्षा भेजें','Verified purchase':'सत्यापित खरीद','Escrow held':'एस्क्रो रोका गया','Escrow released':'एस्क्रो जारी','Dispute raised':'विवाद दर्ज',
  'TRUST PROFILE':'भरोसा प्रोफाइल','Identity & verification':'पहचान और सत्यापन','Platform activity':'प्लेटफॉर्म गतिविधि','About':'परिचय','Produce & quality declarations':'उपज और गुणवत्ता घोषणाएं','Reviews from completed orders':'पूरे हुए ऑर्डरों की समीक्षाएं','Certificate Verified':'प्रमाणपत्र सत्यापित','Certificate Pending':'प्रमाणपत्र लंबित','Inspection Verified':'निरीक्षण सत्यापित',
  'ADMIN DASHBOARD':'एडमिन डैशबोर्ड','Overview':'अवलोकन','People':'लोग','Orders':'ऑर्डर','Listings':'लिस्टिंग','Reviews':'समीक्षाएं','Disputes':'विवाद','Escrow':'एस्क्रो','Total users':'कुल उपयोगकर्ता','Total orders':'कुल ऑर्डर','Escrow held':'एस्क्रो रोका गया','Released to farmers':'किसानों को जारी','Open disputes':'खुले विवाद','Verify certificate':'प्रमाणपत्र सत्यापित करें','Resolve dispute':'विवाद सुलझाएं','Partial refund':'आंशिक रिफंड','Release to farmer':'किसान को भुगतान जारी करें',
  'VOICE ASSISTANT':'वॉइस असिस्टेंट','Speak your way':'अपनी भाषा में बोलें','Multilingual voice UI for the prototype. Integration can be connected later.':'प्रोटोटाइप के लिए बहुभाषी वॉइस UI। वास्तविक इंटीग्रेशन बाद में जोड़ा जा सकता है।','Tap to speak':'बोलने के लिए टैप करें','22-language selector • UI demonstration only':'22 भाषाओं का चयन • केवल UI प्रदर्शन',
  'Profile':'प्रोफाइल','Profile not found':'प्रोफाइल नहीं मिली','This demo profile may have been removed.':'यह डेमो प्रोफाइल हटाई गई हो सकती है।','Back to marketplace':'मार्केटप्लेस पर वापस जाएं','Marketplace':'मार्केटप्लेस','List Crop':'फसल सूचीबद्ध करें','Demand':'मांग','Available Loads':'उपलब्ध लोड','My trips':'मेरी यात्राएं','Incoming Requests':'आने वाले अनुरोध',
  'Farmer rating':'किसान रेटिंग','Driver rating':'ड्राइवर रेटिंग','On-time':'समय पर','Feedback':'प्रतिक्रिया','Reviews':'समीक्षाएं','Rating':'रेटिंग','Region':'क्षेत्र','Certification':'प्रमाणन','Certifications':'प्रमाणपत्र','Quality':'गुणवत्ता','Grade':'ग्रेड','Price':'कीमत','per kg':'प्रति किग्रा','Quantity':'मात्रा','Search':'खोजें','Filter':'फ़िल्टर','Details':'विवरण','View profile':'प्रोफाइल देखें','Back':'वापस','Save':'सहेजें','Cancel':'रद्द करें','Submit':'जमा करें','Close':'बंद करें','Next':'आगे','Previous':'पिछला','Yes':'हां','No':'नहीं','Status':'स्थिति','Date':'तारीख','Action':'कार्रवाई','Total':'कुल','Payment':'भुगतान','Delivery':'डिलीवरी','Driver':'ड्राइवर','Farmer':'किसान','Buyer':'खरीदार'
};

const keys=Object.keys(HI).sort((a,b)=>b.length-a.length);
const escape=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const re=new RegExp(keys.map(escape).join('|'),'gi');
export function translateText(text){
  if(!text||!text.trim()) return text;
  const lead=text.match(/^\s*/)?.[0]||''; const trail=text.match(/\s*$/)?.[0]||''; const core=text.slice(lead.length,text.length-trail.length);
  return lead+core.replace(re,m=>HI[keys.find(k=>k.toLowerCase()===m.toLowerCase())]||m)+trail;
}

function Translator(){const{language}=useLanguage();useEffect(()=>{
  const originals=new WeakMap(); let applying=false;
  const attrs=['placeholder','title','aria-label','alt'];
  const translate=()=>{if(applying)return; applying=true;
    const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT); const nodes=[]; while(walker.nextNode())nodes.push(walker.currentNode);
    nodes.forEach(n=>{if(n.parentElement?.closest('.kc-no-translate'))return; const current=n.nodeValue||''; if(!originals.has(n)){originals.set(n,current);}
      let original=originals.get(n);
      if(language==='hi'){ const desired=translateText(original); if(current===desired) return; if(current!==original){ original=current; originals.set(n,original); } n.nodeValue=translateText(original); }
      else { if(current!==original) n.nodeValue=original; }
    });
    document.querySelectorAll('*').forEach(el=>{if(el.closest('.kc-no-translate'))return; attrs.forEach(a=>{if(!el.hasAttribute(a))return; const key=`data-kc-original-${a}`; if(!el.hasAttribute(key))el.setAttribute(key,el.getAttribute(a)||''); const original=el.getAttribute(key)||''; const desired=language==='hi'?translateText(original):original; if(el.getAttribute(a)!==desired)el.setAttribute(a,desired);});});
    applying=false;
  };
  translate(); const observer=new MutationObserver(()=>{translate()}); observer.observe(document.body,{childList:true,subtree:true,characterData:true});
  return()=>{observer.disconnect();document.querySelectorAll('*').forEach(el=>{if(el.closest('.kc-no-translate'))return; attrs.forEach(a=>{const key=`data-kc-original-${a}`;if(el.hasAttribute(key))el.setAttribute(a,el.getAttribute(key)||'')});});};
},[language]); return null;}
export function LanguageProvider({children}){const[language,setLanguage]=useState(()=>localStorage.getItem('kc-language')||'en');const value=useMemo(()=>({language,setLanguage, toggle:()=>setLanguage(x=>x==='en'?'hi':'en')}),[language]);useEffect(()=>localStorage.setItem('kc-language',language),[language]);return <LanguageContext.Provider value={value}>{children}<Translator/></LanguageContext.Provider>}
export const useLanguage=()=>useContext(LanguageContext);
