import {useMemo,useState} from 'react';
import AppLayout from '../components/AppLayout';
import {getState,updateState} from '../data/demoStore';
import {useAuth} from '../context/AuthContext';

const defaultBasis={maturity:'Fully mature / market-ready',appearance:'Uniform colour and size',damagedPercent:'< 3%',moisture:'Commodity-specific / farmer declared',pestDamage:'None observed',foreignMatter:'< 1%'};

export default function ListCrop(){
 const {user}=useAuth();
 const [saved,setSaved]=useState(false); const [preview,setPreview]=useState(''); const [cropFile,setCropFile]=useState(null); const [certificate,setCertificate]=useState(null);
 const [f,setF]=useState({cropType:'',quantity:'',price:'',region:user?.region||'',grade:'A',certType:'None',certName:'',harvest:'',description:'',deliveryDays:3,...defaultBasis});
 const set=(k,v)=>setF(x=>({...x,[k]:v}));
 const certRequired=f.certType!=='None';
 const certLabel=useMemo(()=>({Organic:'Organic certification',FSSAI:'FSSAI / food-safety document',APEDA:'APEDA / export document',GI:'GI / geographical indication document',Other:'Other certification or test report'})[f.certType]||'', [f.certType]);
 const onImage=e=>{const file=e.target.files?.[0]; if(!file)return; setCropFile(file); const reader=new FileReader(); reader.onload=()=>{setPreview(String(reader.result));}; reader.readAsDataURL(file);};
 const uploadFile=async(file)=>null;
 const submit=async e=>{e.preventDefault();
   const cropUpload=cropFile?await uploadFile(cropFile):null; const certUpload=certificate?await uploadFile(certificate):null;
   const s=getState();
   const certs=['KYC Verified']; if(f.certType!=='None') certs.push(f.certName||certLabel);
   const listing={id:`C-${Date.now()}`,cropType:f.cropType,quantity:Number(f.quantity),pricePerKg:Number(f.price),region:f.region,qualityGrade:f.grade,farmerId:user.userId,farmerName:user.name,farmerRating:4.8,reviews:0,certifications:certs,harvest:f.harvest||'Freshly listed',deliveryDays:Number(f.deliveryDays)||3,minOrder:50,description:f.description||'Fresh produce listed directly by the farmer.',cropImage:cropUpload?.url||preview||null,qualityBasis:{maturity:f.maturity,appearance:f.appearance,damagedPercent:f.damagedPercent,moisture:f.moisture,pestDamage:f.pestDamage,foreignMatter:f.foreignMatter},gradeDeclaredBy:'FARMER',verificationLevel:f.certType==='None'?'FARMER_DECLARED':'CERTIFICATE_PENDING',certificateName:f.certName||certLabel||null,certificateStatus:f.certType==='None'?null:'PENDING_REVIEW',certificateUrl:certUpload?.url||null};
   updateState({listings:[listing,...s.listings]}); setSaved(true); setTimeout(()=>setSaved(false),4500);
 };
 return <AppLayout wide><div className="page-head compact"><div><span className="eyebrow">SELL WITH TRANSPARENCY</span><h1>List your crop / produce</h1><p>Farmers declare quality using measurable parameters. Buyers see exactly what was declared and whether a certificate is only uploaded or verified.</p></div></div>
 <form className="card form-card listing-form" onSubmit={submit}>
  <div className="form-section-title"><span>01</span><div><b>Produce details</b><small>What are you selling?</small></div></div>
  <div className="form-grid"><label>Crop / product<input required value={f.cropType} onChange={e=>set('cropType',e.target.value)} placeholder="e.g. Onion, Rose, Rice"/></label><label>Available quantity (kg)<input required type="number" min="1" value={f.quantity} onChange={e=>set('quantity',e.target.value)} placeholder="1000"/></label><label>Price per kg (₹)<input required type="number" min="1" value={f.price} onChange={e=>set('price',e.target.value)} placeholder="45"/></label><label>Origin / region<input value={f.region} onChange={e=>set('region',e.target.value)}/></label><label>Harvest / availability<input value={f.harvest} onChange={e=>set('harvest',e.target.value)} placeholder="Harvested 1 day ago"/></label><label>Expected delivery days<input type="number" min="1" max="30" value={f.deliveryDays||3} onChange={e=>set('deliveryDays',e.target.value)}/></label></div>
  <div className="form-section-title"><span>02</span><div><b>Quality declaration</b><small>This is a farmer declaration, not an automatic lab certification.</small></div></div>
  <div className="quality-notice"><strong>🌱 How Grade {f.grade} is determined</strong><span>Enter observable quality parameters below. KhetConnect labels the result <b>Farmer Declared</b> until supporting evidence is verified.</span></div>
  <div className="form-grid"><label>Quality grade<select value={f.grade} onChange={e=>set('grade',e.target.value)}><option>A+</option><option>A</option><option>B</option><option>C</option></select></label><label>Maturity<input value={f.maturity} onChange={e=>set('maturity',e.target.value)}/></label><label>Appearance / uniformity<input value={f.appearance} onChange={e=>set('appearance',e.target.value)}/></label><label>Damaged produce<input value={f.damagedPercent} onChange={e=>set('damagedPercent',e.target.value)} placeholder="e.g. < 2%"/></label><label>Moisture<input value={f.moisture} onChange={e=>set('moisture',e.target.value)} placeholder="e.g. 12%"/></label><label>Pest / disease damage<input value={f.pestDamage} onChange={e=>set('pestDamage',e.target.value)}/></label><label>Foreign matter<input value={f.foreignMatter} onChange={e=>set('foreignMatter',e.target.value)}/></label><label className="span-2">Description<textarea value={f.description} onChange={e=>set('description',e.target.value)} placeholder="Packing, variety, storage, handling and other useful details..."/></label></div>
  <div className="form-section-title"><span>03</span><div><b>Produce photo & certification</b><small>Photos help buyers cross-check what they receive.</small></div></div>
  <div className="upload-grid"><label className="upload-box">📷 <b>Crop / produce photo</b><small>JPG/PNG · prototype preview</small><input type="file" accept="image/*" onChange={onImage}/></label>{preview&&<div className="photo-preview"><img src={preview} alt="Crop preview"/><span>Buyer preview</span></div>}<div className="certificate-box"><label>Certification type<select value={f.certType} onChange={e=>set('certType',e.target.value)}><option>None</option><option>Organic</option><option>FSSAI</option><option>APEDA</option><option>GI</option><option>Other</option></select></label>{certRequired&&<><label>{certLabel}<input required value={f.certName} onChange={e=>set('certName',e.target.value)} placeholder="Certificate / document name"/></label><label className="upload-inline">📄 Upload certificate / report<input type="file" accept="image/*,.pdf" onChange={e=>setCertificate(e.target.files?.[0]||null)}/><small>{certificate?certificate.name:'No file selected'} · status will be Pending Review</small></label></>}</div></div>
  <div className="buyer-preview"><div><b>Buyer will see</b><span>Grade {f.grade} · Farmer Declared</span><span>{certRequired?'📄 Certificate uploaded · Pending Admin Verification':'No special certification claimed'}</span><span>📷 {preview?'Crop photo added':'Crop photo not added'}</span></div><div><b>Anti-loophole rule</b><span>Ratings come from completed orders only.</span><span>One review per completed order.</span><span>Admin can verify certificates and review disputes.</span></div></div>
  <button className="btn btn-primary btn-block">Publish Listing →</button>{saved&&<div className="alert success">✓ Listing published. Buyers can now see the declared quality basis, photo and certificate status.</div>}
 </form></AppLayout>
}
