import {useMemo,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import AppLayout from '../components/AppLayout';
import {createOrder,getState,rankListings} from '../data/demoStore';
import {useAuth} from '../context/AuthContext';

const emoji=x=>x.includes('Mango')?'🥭':x==='Rose'?'🌹':x==='Rice'?'🌾':x==='Banana'?'🍌':x.includes('Chilli')?'🌶️':x==='Tomato'?'🍅':'🧅';
export default function Marketplace(){
 const{user}=useAuth();const nav=useNavigate();const[q,setQ]=useState('');const[region,setRegion]=useState('All India');const[selected,setSelected]=useState(null);const[qty,setQty]=useState(100);const s=getState();
 const items=useMemo(()=>{const filtered=s.listings.filter(x=>(!q||`${x.cropType} ${x.farmerName} ${x.region}`.toLowerCase().includes(q.toLowerCase()))&&(region==='All India'||x.region.includes(region)));return rankListings(filtered)},[q,region,s.listings]);
 const place=()=>{const qn=Math.max(selected.minOrder,Math.min(Number(qty),selected.quantity));const o=createOrder(selected,user.userId,qn);setSelected(null);nav(`/orders/${o.id}`)};
 return <AppLayout wide><div className="page-head"><div><span className="eyebrow">DIRECT FARM MARKET · RANKED BY TRUST</span><h1>Find fresh produce</h1><p>Search crops and farmers. Higher verified-order ratings are recommended first, while certificate status and declared quality remain visible.</p></div><div className="market-count">{items.length}<small>listings matched</small></div></div>
 <div className="search-bar"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search onion, mango, farmer, region..."/><select value={region} onChange={e=>setRegion(e.target.value)}><option>All India</option><option>Maharashtra</option><option>Gujarat</option><option>Tamil Nadu</option><option>West Bengal</option><option>Karnataka</option><option>Kerala</option><option>Andhra Pradesh</option></select></div>
 <div className="info-strip"><b>🏆 Recommended first</b><span>Farmer rating + completed-order review history influence ranking.</span><b>🔒 Escrow protected</b><span>Payment is held until buyer confirms receipt.</span><b>⚠ Honest grading</b><span>Grade is farmer-declared unless certificate/inspection evidence is verified.</span></div>
 <div className="listing-grid">{items.map(x=><article className="listing-card" key={x.id}><div className="crop-visual">{x.cropImage?<img src={x.cropImage} alt={x.cropType}/>:emoji(x.cropType)}<span>Grade {x.qualityGrade}</span></div><div className="listing-body"><div className="listing-top"><div><h3>{x.cropType}</h3><small>📍 {x.region}</small></div><strong>₹{x.pricePerKg}<small>/kg</small></strong></div><div className="grade-line"><span className="status orange">{x.verificationLevel==='CERTIFICATE_VERIFIED'?'Certificate Verified':'Farmer Declared'}</span>{x.certificateName&&<span className="status green">📄 {x.certificateName}</span>}</div><p>{x.description}</p><div className="quality-mini"><b>Quality basis</b><span>Damage {x.qualityBasis?.damagedPercent||'declared'} · {x.qualityBasis?.appearance||'appearance declared'}</span></div><div className="tag-row">{x.certifications.slice(0,3).map(c=><span key={c}>✓ {c}</span>)}</div><div className="farmer-line"><div className="avatar">{x.farmerName.charAt(0)}</div><div><Link to={`/trust-profile/${x.farmerId}`}><b>{x.farmerName}</b></Link><small>⭐ {x.farmerRating} · {x.reviews} verified reviews</small></div><span className="recommended">TOP</span></div><div className="listing-meta"><span>📦 {x.quantity.toLocaleString('en-IN')} kg available</span><span>🚚 {x.deliveryDays} days est.</span></div><button className="btn btn-primary btn-block" onClick={()=>{setSelected(x);setQty(x.minOrder)}}>Start Order →</button></div></article>)}</div>
 {selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">ORDER PREVIEW · ESCROW</span><h2>{selected.cropType} from {selected.farmerName}</h2>{selected.cropImage&&<img className="modal-crop-image" src={selected.cropImage} alt="Produce"/>}<div className="order-summary"><div><span>Price</span><b>₹{selected.pricePerKg}/kg</b></div><div><span>Delivery</span><b>{selected.deliveryDays} days</b></div><div><span>Farmer</span><b>⭐ {selected.farmerRating}</b></div></div><div className="quality-detail"><b>Grade {selected.qualityGrade} · {selected.verificationLevel==='CERTIFICATE_VERIFIED'?'Certificate Verified':'Farmer Declared'}</b><span>Based on: {selected.qualityBasis?.maturity}; damage {selected.qualityBasis?.damagedPercent}; moisture {selected.qualityBasis?.moisture}.</span>{selected.certificateName&&<span>📄 {selected.certificateName} · {selected.certificateStatus}</span>}</div><label>Quantity (kg) · minimum {selected.minOrder}</label><input type="number" min={selected.minOrder} max={selected.quantity} value={qty} onChange={e=>setQty(e.target.value)}/><div className="total-box"><span>Escrow amount</span><strong>₹{(Number(qty||0)*selected.pricePerKg).toLocaleString('en-IN')}</strong><small>Held safely until you confirm delivery and product quality.</small></div><button className="btn btn-primary btn-block" onClick={place}>Place Order & Hold Escrow →</button></div></div>}
 </AppLayout>
}
