import {useParams,Link} from 'react-router-dom';
import AppLayout from '../components/AppLayout';
import {getReviewsForDriver,getReviewsForFarmer,getState,getUser,roleLabel} from '../data/demoStore';
export default function TrustProfile(){
 const{id}=useParams();const p=getUser(id);const st=getState();
 if(!p)return <AppLayout><div className="empty-state"><h2>Profile not found</h2><p className="muted">This demo profile may have been removed.</p><Link className="btn btn-primary" to="/marketplace">Back to marketplace</Link></div></AppLayout>;
 const rs=p.role==='FARMER'?getReviewsForFarmer(id):getReviewsForDriver(id); const listings=st.listings.filter(x=>x.farmerId===id);
 return <AppLayout wide><div className="trust-cover"><div className="profile-avatar">{p.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><span className="eyebrow">TRUST PROFILE · {p.kyc}</span><h1>{p.name}</h1><p>{roleLabel(p.role)} · 📍 {p.region}</p></div><div className="trust-score"><b>⭐ {p.rating}</b><small>{p.reviews} verified reviews</small></div></div>
 <div className="detail-grid"><div className="card"><h3>Identity & verification</h3>{p.badges.map(x=><div className="verify-row" key={x}>✓ <span>{x}</span><b>Verified</b></div>)}<div className="verify-row">✓ <span>Platform activity</span><b>Tracked</b></div></div><div className="card"><h3>About</h3><p>{p.bio}</p>{p.farm&&<p>🌱 {p.farm}</p>}{p.vehicle&&<p>🚚 {p.vehicle}</p>}{p.buyerType&&<p>🛒 {p.buyerType}</p>}</div></div>
 {p.role==='FARMER'&&<div className="card"><div className="section-head"><h3>Produce & quality declarations</h3><span>{listings.length} listings</span></div><div className="profile-listings">{listings.map(x=><div className="profile-listing" key={x.id}>{x.cropImage&&<img src={x.cropImage} alt={x.cropType}/>}<div><b>{x.cropType} · Grade {x.qualityGrade}</b><small>₹{x.pricePerKg}/kg · {x.quantity} kg · {x.region}</small><span className={`status ${x.verificationLevel==='CERTIFICATE_VERIFIED'?'green':'gold'}`}>{x.verificationLevel==='CERTIFICATE_VERIFIED'?'✓ Certificate Verified':'Farmer Declared'}</span>{x.certificateName&&<small>📄 {x.certificateName} · {x.certificateStatus}</small>}</div></div>)}</div></div>}
 <div className="card"><h3>Reviews from completed orders</h3>{rs.length?rs.map(r=><div className="review-item" key={r.id}><div><b>{r.buyer}</b><small>{r.date} · ✓ Verified purchase</small></div><span>⭐ {p.role==='FARMER'?r.farmerRating:r.driverRating}</span><p>{r.comment}</p>{p.role==='TRUCK_DRIVER'&&r.onTime&&<small>On-time delivery: ⭐ {r.onTime}/5</small>}</div>):<p className="muted">No reviews yet.</p>}</div><Link className="back-link" to="/marketplace">← Back</Link></AppLayout>
}
